name: dogemp
description: DOGemP

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  intl: ^0.17.0
  just_the_tooltip: ^0.0.11+2
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/github.svg
    - assets/twitch.svg
    - assets/youtube.svg